version: "3.8"

services:
  php-apache:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./controllers:/var/www/html
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: Chollos_Database
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  db_data:
